export enum ContractStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  COMPLETION_REQUESTED = 'COMPLETION_REQUESTED',
  COMPLETED = 'COMPLETED',
  APPROVED = 'APPROVED',
}

export enum BankingTransactionType {
  CONTRACT_INCOME = 'CONTRACT_INCOME',
  PAYROLL_EXPENSE = 'PAYROLL_EXPENSE',
  EMPLOYEE_WAGE_CREDIT = 'EMPLOYEE_WAGE_CREDIT',
}
