import os

FACE_DATASET_ROOT = os.getenv('FACE_DATASET_ROOT', './facial-recognition')
CASIA_WEBFACE_PATH = os.getenv('CASIA_WEBFACE_PATH', f'{FACE_DATASET_ROOT}/CASIA-WebFace')
LFW_PATH = os.getenv('LFW_PATH', f'{FACE_DATASET_ROOT}/LFW')
CELEBA_SPOOF_PATH = os.getenv('CELEBA_SPOOF_PATH', f'{FACE_DATASET_ROOT}/CelebA-Spoof')
CASIA_FASD_PATH = os.getenv('CASIA_FASD_PATH', f'{FACE_DATASET_ROOT}/CASIA-FASD')
